name = "Kindling"
author = "Bralyn"
version = "0.4.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11758bbbce4829ccbef67c845a221aa7f47b518819b352b48cd337c43b718724"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
