name = "Kindling"
author = "Bralyn"
version = "0.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f357c70e5950b3c35ed885d5e309968e0280199ba37aad0390bbad53b1fdf3c1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
